/**
 * mechanic-kpi.js — read access to mechanic_kpi_snapshots: periodic
 * technician attendance/billing/utilization reports brought in from an
 * external report (see scripts/import-mechanic-kpi.js), not generated by
 * this platform. Read-only on purpose — there is no "create a snapshot"
 * flow in the app; new periods arrive the same way this one did, via the
 * import script, so a future report can be dropped in the same way.
 *
 *   GET /api/mechanic-kpi/periods    distinct periods available, newest first
 *   GET /api/mechanic-kpi/snapshots  the report rows for one period
 */
import { Router } from 'express';
import { query } from '../lib/database.js';
import { authMiddleware } from '../middleware/auth.js';

const router = Router();
router.use(authMiddleware);

router.get('/periods', async (req, res) => {
  try {
    const rows = await query(
      `SELECT period_start, period_end, COUNT(*) AS technician_count
         FROM mechanic_kpi_snapshots
        WHERE workshop_id = ?
        GROUP BY period_start, period_end
        ORDER BY period_start DESC`,
      [req.workshopId]
    );
    return res.json({ success: true, data: rows });
  } catch (err) {
    console.error('[mechanic-kpi] periods error:', err.message);
    return res.status(500).json({ success: false, message: 'Failed to load KPI periods' });
  }
});

router.get('/snapshots', async (req, res) => {
  try {
    const { period_start, period_end } = req.query;
    const where = ['s.workshop_id = ?'];
    const params = [req.workshopId];
    if (period_start) { where.push('s.period_start = ?'); params.push(period_start); }
    if (period_end) { where.push('s.period_end = ?'); params.push(period_end); }
    const clause = where.join(' AND ');

    const rows = await query(
      `SELECT s.id, s.mechanic_id, s.period_start, s.period_end, s.employee_code, s.designation,
              s.days_present, s.avail_hrs, s.ot_hrs, s.total_hrs, s.worked_hrs,
              s.prod_hrs_pct, s.idle_hrs_pct, s.billed_value, s.billed_hrs, s.billed_hours,
              s.utilization_pct, s.productivity_pct, s.efficiency_pct,
              m.full_name AS mechanic_name, m.specialty
         FROM mechanic_kpi_snapshots s
         JOIN mechanics m ON m.id = s.mechanic_id
        WHERE ${clause}
        ORDER BY s.efficiency_pct DESC`,
      params
    );

    const summary = rows.length ? {
      technician_count: rows.length,
      total_billed_value: rows.reduce((a, r) => a + Number(r.billed_value || 0), 0),
      avg_utilization_pct: Math.round(rows.reduce((a, r) => a + Number(r.utilization_pct || 0), 0) / rows.length),
      avg_productivity_pct: Math.round(rows.reduce((a, r) => a + Number(r.productivity_pct || 0), 0) / rows.length),
      avg_efficiency_pct: Math.round(rows.reduce((a, r) => a + Number(r.efficiency_pct || 0), 0) / rows.length),
    } : null;

    return res.json({ success: true, data: rows, summary });
  } catch (err) {
    console.error('[mechanic-kpi] snapshots error:', err.message);
    return res.status(500).json({ success: false, message: 'Failed to load KPI snapshots' });
  }
});

export default router;
