-- Seed countries table with all world phone codes
-- Sorted by region priority: Gulf first, then alphabetical within regions

INSERT INTO countries (name, iso, phone_code, flag, region, sort_order) VALUES
-- Gulf / Middle East (priority region)
('United Arab Emirates', 'AE', '+971', '🇦🇪', 'Middle East', 1),
('Saudi Arabia', 'SA', '+966', '🇸🇦', 'Middle East', 2),
('Bahrain', 'BH', '+973', '🇧🇭', 'Middle East', 3),
('Oman', 'OM', '+968', '🇴🇲', 'Middle East', 4),
('Kuwait', 'KW', '+965', '🇰🇼', 'Middle East', 5),
('Qatar', 'QA', '+974', '🇶🇦', 'Middle East', 6),
('Jordan', 'JO', '+962', '🇯🇴', 'Middle East', 7),
('Lebanon', 'LB', '+961', '🇱🇧', 'Middle East', 8),
('Iraq', 'IQ', '+964', '🇮🇶', 'Middle East', 9),
('Israel', 'IL', '+972', '🇮🇱', 'Middle East', 10),
('Palestine', 'PS', '+970', '🇵🇸', 'Middle East', 11),
('Syria', 'SY', '+963', '🇸🇾', 'Middle East', 12),
('Yemen', 'YE', '+967', '🇾🇪', 'Middle East', 13),
('Iran', 'IR', '+98', '🇮🇷', 'Middle East', 14),
-- North Africa
('Egypt', 'EG', '+20', '🇪🇬', 'North Africa', 20),
('Morocco', 'MA', '+212', '🇲🇦', 'North Africa', 21),
('Tunisia', 'TN', '+216', '🇹🇳', 'North Africa', 22),
('Algeria', 'DZ', '+213', '🇩🇿', 'North Africa', 23),
('Libya', 'LY', '+218', '🇱🇾', 'North Africa', 24),
('Sudan', 'SD', '+249', '🇸🇩', 'North Africa', 25),
-- South Asia
('India', 'IN', '+91', '🇮🇳', 'South Asia', 30),
('Pakistan', 'PK', '+92', '🇵🇰', 'South Asia', 31),
('Bangladesh', 'BD', '+880', '🇧🇩', 'South Asia', 32),
('Sri Lanka', 'LK', '+94', '🇱🇰', 'South Asia', 33),
('Nepal', 'NP', '+977', '🇳🇵', 'South Asia', 34),
('Afghanistan', 'AF', '+93', '🇦🇫', 'South Asia', 35),
('Maldives', 'MV', '+960', '🇲🇻', 'South Asia', 36),
('Bhutan', 'BT', '+975', '🇧🇹', 'South Asia', 37),
-- Southeast Asia
('Philippines', 'PH', '+63', '🇵🇭', 'Southeast Asia', 40),
('Indonesia', 'ID', '+62', '🇮🇩', 'Southeast Asia', 41),
('Malaysia', 'MY', '+60', '🇲🇾', 'Southeast Asia', 42),
('Singapore', 'SG', '+65', '🇸🇬', 'Southeast Asia', 43),
('Thailand', 'TH', '+66', '🇹🇭', 'Southeast Asia', 44),
('Vietnam', 'VN', '+84', '🇻🇳', 'Southeast Asia', 45),
('Myanmar', 'MM', '+95', '🇲🇲', 'Southeast Asia', 46),
('Cambodia', 'KH', '+855', '🇰🇭', 'Southeast Asia', 47),
('Laos', 'LA', '+856', '🇱🇦', 'Southeast Asia', 48),
('Brunei', 'BN', '+673', '🇧🇳', 'Southeast Asia', 49),
('Timor-Leste', 'TL', '+670', '🇹🇱', 'Southeast Asia', 50),
-- East Asia
('China', 'CN', '+86', '🇨🇳', 'East Asia', 55),
('Japan', 'JP', '+81', '🇯🇵', 'East Asia', 56),
('South Korea', 'KR', '+82', '🇰🇷', 'East Asia', 57),
('Hong Kong', 'HK', '+852', '🇭🇰', 'East Asia', 58),
('Macau', 'MO', '+853', '🇲🇴', 'East Asia', 59),
('Taiwan', 'TW', '+886', '🇹🇼', 'East Asia', 60),
('Mongolia', 'MN', '+976', '🇲🇳', 'East Asia', 61),
('North Korea', 'KP', '+850', '🇰🇵', 'East Asia', 62),
-- Europe — Western
('United Kingdom', 'GB', '+44', '🇬🇧', 'Europe', 70),
('France', 'FR', '+33', '🇫🇷', 'Europe', 71),
('Germany', 'DE', '+49', '🇩🇪', 'Europe', 72),
('Italy', 'IT', '+39', '🇮🇹', 'Europe', 73),
('Spain', 'ES', '+34', '🇪🇸', 'Europe', 74),
('Portugal', 'PT', '+351', '🇵🇹', 'Europe', 75),
('Netherlands', 'NL', '+31', '🇳🇱', 'Europe', 76),
('Belgium', 'BE', '+32', '🇧🇪', 'Europe', 77),
('Switzerland', 'CH', '+41', '🇨🇭', 'Europe', 78),
('Austria', 'AT', '+43', '🇦🇹', 'Europe', 79),
('Ireland', 'IE', '+353', '🇮🇪', 'Europe', 80),
('Luxembourg', 'LU', '+352', '🇱🇺', 'Europe', 81),
('Monaco', 'MC', '+377', '🇲🇨', 'Europe', 82),
('Andorra', 'AD', '+376', '🇦🇩', 'Europe', 83),
('Gibraltar', 'GI', '+350', '🇬🇮', 'Europe', 84),
('Liechtenstein', 'LI', '+423', '🇱🇮', 'Europe', 85),
('San Marino', 'SM', '+378', '🇸🇲', 'Europe', 86),
('Vatican City', 'VA', '+379', '🇻🇦', 'Europe', 87),
-- Europe — Northern
('Sweden', 'SE', '+46', '🇸🇪', 'Europe', 90),
('Norway', 'NO', '+47', '🇳🇴', 'Europe', 91),
('Denmark', 'DK', '+45', '🇩🇰', 'Europe', 92),
('Finland', 'FI', '+358', '🇫🇮', 'Europe', 93),
('Iceland', 'IS', '+354', '🇮🇸', 'Europe', 94),
('Faroe Islands', 'FO', '+298', '🇫🇴', 'Europe', 95),
-- Europe — Eastern
('Poland', 'PL', '+48', '🇵🇱', 'Europe', 100),
('Czech Republic', 'CZ', '+420', '🇨🇿', 'Europe', 101),
('Slovakia', 'SK', '+421', '🇸🇰', 'Europe', 102),
('Hungary', 'HU', '+36', '🇭🇺', 'Europe', 103),
('Romania', 'RO', '+40', '🇷🇴', 'Europe', 104),
('Bulgaria', 'BG', '+359', '🇧🇬', 'Europe', 105),
('Ukraine', 'UA', '+380', '🇺🇦', 'Europe', 106),
('Russia', 'RU', '+7', '🇷🇺', 'Europe', 107),
('Belarus', 'BY', '+375', '🇧🇾', 'Europe', 108),
('Moldova', 'MD', '+373', '🇲🇩', 'Europe', 109),
('Lithuania', 'LT', '+370', '🇱🇹', 'Europe', 110),
('Latvia', 'LV', '+371', '🇱🇻', 'Europe', 111),
('Estonia', 'EE', '+372', '🇪🇪', 'Europe', 112),
-- Europe — Balkans
('Greece', 'GR', '+30', '🇬🇷', 'Europe', 120),
('Turkey', 'TR', '+90', '🇹🇷', 'Europe', 121),
('Croatia', 'HR', '+385', '🇭🇷', 'Europe', 122),
('Slovenia', 'SI', '+386', '🇸🇮', 'Europe', 123),
('Serbia', 'RS', '+381', '🇷🇸', 'Europe', 124),
('Bosnia and Herzegovina', 'BA', '+387', '🇧🇦', 'Europe', 125),
('North Macedonia', 'MK', '+389', '🇲🇰', 'Europe', 126),
('Montenegro', 'ME', '+382', '🇲🇪', 'Europe', 127),
('Kosovo', 'XK', '+383', '🇽🇰', 'Europe', 128),
('Albania', 'AL', '+355', '🇦🇱', 'Europe', 129),
('Cyprus', 'CY', '+357', '🇨🇾', 'Europe', 130),
('Malta', 'MT', '+356', '🇲🇹', 'Europe', 131),
-- Central Asia
('Kazakhstan', 'KZ', '+7', '🇰🇿', 'Central Asia', 140),
('Uzbekistan', 'UZ', '+998', '🇺🇿', 'Central Asia', 141),
('Turkmenistan', 'TM', '+993', '🇹🇲', 'Central Asia', 142),
('Kyrgyzstan', 'KG', '+996', '🇰🇬', 'Central Asia', 143),
('Tajikistan', 'TJ', '+992', '🇹🇯', 'Central Asia', 144),
-- Caucasus
('Azerbaijan', 'AZ', '+994', '🇦🇿', 'Caucasus', 150),
('Georgia', 'GE', '+995', '🇬🇪', 'Caucasus', 151),
('Armenia', 'AM', '+374', '🇦🇲', 'Caucasus', 152),
-- North America
('United States', 'US', '+1', '🇺🇸', 'North America', 160),
('Canada', 'CA', '+1', '🇨🇦', 'North America', 161),
('Mexico', 'MX', '+52', '🇲🇽', 'North America', 162),
-- Central America
('Guatemala', 'GT', '+502', '🇬🇹', 'Central America', 170),
('El Salvador', 'SV', '+503', '🇸🇻', 'Central America', 171),
('Honduras', 'HN', '+504', '🇭🇳', 'Central America', 172),
('Nicaragua', 'NI', '+505', '🇳🇮', 'Central America', 173),
('Costa Rica', 'CR', '+506', '🇨🇷', 'Central America', 174),
('Panama', 'PA', '+507', '🇵🇦', 'Central America', 175),
('Belize', 'BZ', '+501', '🇧🇿', 'Central America', 176),
-- Caribbean
('Jamaica', 'JM', '+1', '🇯🇲', 'Caribbean', 180),
('Trinidad and Tobago', 'TT', '+1', '🇹🇹', 'Caribbean', 181),
('Bahamas', 'BS', '+1', '🇧🇸', 'Caribbean', 182),
('Barbados', 'BB', '+1', '🇧🇧', 'Caribbean', 183),
('Dominican Republic', 'DO', '+1', '🇩🇴', 'Caribbean', 184),
('Puerto Rico', 'PR', '+1', '🇵🇷', 'Caribbean', 185),
('Cuba', 'CU', '+53', '🇨🇺', 'Caribbean', 186),
('Haiti', 'HT', '+509', '🇭🇹', 'Caribbean', 187),
('Antigua and Barbuda', 'AG', '+1', '🇦🇬', 'Caribbean', 188),
('Grenada', 'GD', '+1', '🇬🇩', 'Caribbean', 189),
('Saint Lucia', 'LC', '+1', '🇱🇨', 'Caribbean', 190),
('Saint Vincent', 'VC', '+1', '🇻🇨', 'Caribbean', 191),
('Saint Kitts and Nevis', 'KN', '+1', '🇰🇳', 'Caribbean', 192),
('Dominica', 'DM', '+1', '🇩🇲', 'Caribbean', 193),
('Curaçao', 'CW', '+599', '🇨🇼', 'Caribbean', 194),
('Aruba', 'AW', '+297', '🇦🇼', 'Caribbean', 195),
('Cayman Islands', 'KY', '+1', '🇰🇾', 'Caribbean', 196),
('Bermuda', 'BM', '+1', '🇧🇲', 'Caribbean', 197),
('US Virgin Islands', 'VI', '+1', '🇻🇮', 'Caribbean', 198),
('British Virgin Islands', 'VG', '+1', '🇻🇬', 'Caribbean', 199),
('Turks and Caicos', 'TC', '+1', '🇹🇨', 'Caribbean', 200),
-- South America
('Brazil', 'BR', '+55', '🇧🇷', 'South America', 210),
('Argentina', 'AR', '+54', '🇦🇷', 'South America', 211),
('Chile', 'CL', '+56', '🇨🇱', 'South America', 212),
('Colombia', 'CO', '+57', '🇨🇴', 'South America', 213),
('Peru', 'PE', '+51', '🇵🇪', 'South America', 214),
('Venezuela', 'VE', '+58', '🇻🇪', 'South America', 215),
('Ecuador', 'EC', '+593', '🇪🇨', 'South America', 216),
('Bolivia', 'BO', '+591', '🇧🇴', 'South America', 217),
('Paraguay', 'PY', '+595', '🇵🇾', 'South America', 218),
('Uruguay', 'UY', '+598', '🇺🇾', 'South America', 219),
('Guyana', 'GY', '+592', '🇬🇾', 'South America', 220),
('Suriname', 'SR', '+597', '🇸🇷', 'South America', 221),
('French Guiana', 'GF', '+594', '🇬🇫', 'South America', 222),
('Falkland Islands', 'FK', '+500', '🇫🇰', 'South America', 223),
-- West Africa
('Nigeria', 'NG', '+234', '🇳🇬', 'West Africa', 230),
('Ghana', 'GH', '+233', '🇬🇭', 'West Africa', 231),
('Ivory Coast', 'CI', '+225', '🇨🇮', 'West Africa', 232),
('Senegal', 'SN', '+221', '🇸🇳', 'West Africa', 233),
('Mali', 'ML', '+223', '🇲🇱', 'West Africa', 234),
('Burkina Faso', 'BF', '+226', '🇧🇫', 'West Africa', 235),
('Niger', 'NE', '+227', '🇳🇪', 'West Africa', 236),
('Guinea', 'GN', '+224', '🇬🇳', 'West Africa', 237),
('Guinea-Bissau', 'GW', '+245', '🇬🇼', 'West Africa', 238),
('Gambia', 'GM', '+220', '🇬🇲', 'West Africa', 239),
('Sierra Leone', 'SL', '+232', '🇸🇱', 'West Africa', 240),
('Liberia', 'LR', '+231', '🇱🇷', 'West Africa', 241),
('Togo', 'TG', '+228', '🇹🇬', 'West Africa', 242),
('Benin', 'BJ', '+229', '🇧🇯', 'West Africa', 243),
('Mauritania', 'MR', '+222', '🇲🇷', 'West Africa', 244),
('Cape Verde', 'CV', '+238', '🇨🇻', 'West Africa', 245),
-- East Africa
('Kenya', 'KE', '+254', '🇰🇪', 'East Africa', 250),
('Tanzania', 'TZ', '+255', '🇹🇿', 'East Africa', 251),
('Uganda', 'UG', '+256', '🇺🇬', 'East Africa', 252),
('Ethiopia', 'ET', '+251', '🇪🇹', 'East Africa', 253),
('Rwanda', 'RW', '+250', '🇷🇼', 'East Africa', 254),
('Burundi', 'BI', '+257', '🇧🇮', 'East Africa', 255),
('Somalia', 'SO', '+252', '🇸🇴', 'East Africa', 256),
('Djibouti', 'DJ', '+253', '🇩🇯', 'East Africa', 257),
('Eritrea', 'ER', '+291', '🇪🇷', 'East Africa', 258),
('South Sudan', 'SS', '+211', '🇸🇸', 'East Africa', 259),
('Mozambique', 'MZ', '+258', '🇲🇿', 'East Africa', 260),
('Madagascar', 'MG', '+261', '🇲🇬', 'East Africa', 261),
('Malawi', 'MW', '+265', '🇲🇼', 'East Africa', 262),
('Zambia', 'ZM', '+260', '🇿🇲', 'East Africa', 263),
('Zimbabwe', 'ZW', '+263', '🇿🇼', 'East Africa', 264),
('Mauritius', 'MU', '+230', '🇲🇺', 'East Africa', 265),
('Seychelles', 'SC', '+248', '🇸🇨', 'East Africa', 266),
('Comoros', 'KM', '+269', '🇰🇲', 'East Africa', 267),
('Réunion', 'RE', '+262', '🇷🇪', 'East Africa', 268),
('Mayotte', 'YT', '+262', '🇾🇹', 'East Africa', 269),
-- Central Africa
('DR Congo', 'CD', '+243', '🇨🇩', 'Central Africa', 280),
('Cameroon', 'CM', '+237', '🇨🇲', 'Central Africa', 281),
('Gabon', 'GA', '+241', '🇬🇦', 'Central Africa', 282),
('Congo', 'CG', '+242', '🇨🇬', 'Central Africa', 283),
('Central African Republic', 'CF', '+236', '🇨🇫', 'Central Africa', 284),
('Chad', 'TD', '+235', '🇹🇩', 'Central Africa', 285),
('Equatorial Guinea', 'GQ', '+240', '🇬🇶', 'Central Africa', 286),
('São Tomé and Príncipe', 'ST', '+239', '🇸🇹', 'Central Africa', 287),
-- Southern Africa
('South Africa', 'ZA', '+27', '🇿🇦', 'Southern Africa', 290),
('Botswana', 'BW', '+267', '🇧🇼', 'Southern Africa', 291),
('Namibia', 'NA', '+264', '🇳🇦', 'Southern Africa', 292),
('Angola', 'AO', '+244', '🇦🇴', 'Southern Africa', 293),
('Lesotho', 'LS', '+266', '🇱🇸', 'Southern Africa', 294),
('Eswatini', 'SZ', '+268', '🇸🇿', 'Southern Africa', 295),
-- Oceania
('Australia', 'AU', '+61', '🇦🇺', 'Oceania', 300),
('New Zealand', 'NZ', '+64', '🇳🇿', 'Oceania', 301),
('Papua New Guinea', 'PG', '+675', '🇵🇬', 'Oceania', 302),
('Fiji', 'FJ', '+679', '🇫🇯', 'Oceania', 303),
('Samoa', 'WS', '+685', '🇼🇸', 'Oceania', 304),
('Tonga', 'TO', '+676', '🇹🇴', 'Oceania', 305),
('Solomon Islands', 'SB', '+677', '🇸🇧', 'Oceania', 306),
('Vanuatu', 'VU', '+678', '🇻🇺', 'Oceania', 307),
('Kiribati', 'KI', '+686', '🇰🇮', 'Oceania', 308),
('Micronesia', 'FM', '+691', '🇫🇲', 'Oceania', 309),
('Marshall Islands', 'MH', '+692', '🇲🇭', 'Oceania', 310),
('Palau', 'PW', '+680', '🇵🇼', 'Oceania', 311),
('Nauru', 'NR', '+674', '🇳🇷', 'Oceania', 312),
('Tuvalu', 'TV', '+688', '🇹🇻', 'Oceania', 313),
('Cook Islands', 'CK', '+682', '🇨🇰', 'Oceania', 314),
('Niue', 'NU', '+683', '🇳🇺', 'Oceania', 315),
('French Polynesia', 'PF', '+689', '🇵🇫', 'Oceania', 316),
('New Caledonia', 'NC', '+687', '🇳🇨', 'Oceania', 317),
('Wallis and Futuna', 'WF', '+681', '🇼🇫', 'Oceania', 318),
('Guam', 'GU', '+1', '🇬🇺', 'Oceania', 319),
('American Samoa', 'AS', '+1', '🇦🇸', 'Oceania', 320),
('Northern Mariana Islands', 'MP', '+1', '🇲🇵', 'Oceania', 321),
-- Territories
('Saint Helena', 'SH', '+290', '🇸🇭', 'Other', 400),
('Ascension Island', 'AC', '+247', '🇦🇨', 'Other', 401),
('British Indian Ocean Territory', 'IO', '+246', '🇮🇴', 'Other', 402),
('Norfolk Island', 'NF', '+672', '🇳🇫', 'Other', 403),
('South Georgia', 'GS', '+500', '🇬🇸', 'Other', 404),
('Guadeloupe', 'GP', '+590', '🇬🇵', 'Other', 405),
('Martinique', 'MQ', '+596', '🇲🇶', 'Other', 406),
('Saint Pierre and Miquelon', 'PM', '+508', '🇵🇲', 'Other', 407),
('Greenland', 'GL', '+299', '🇬🇱', 'Other', 408)
ON DUPLICATE KEY UPDATE name=VALUES(name), phone_code=VALUES(phone_code), flag=VALUES(flag), region=VALUES(region), sort_order=VALUES(sort_order);
