-- ═══════════════════════════════════════════════════════════════════════
-- mechanic_kpi_snapshots — periodic technician performance reports
-- (attendance, hours, billed value, utilization/productivity/efficiency)
-- brought in from an external report (payroll/attendance system), not
-- generated by this platform.
--
-- No FK-strict uniqueness on (mechanic_id, period_start, period_end): the
-- source report itself carries more than one row for the same technician
-- within the same period for a few people (e.g. TN0272, TN0252, TN0254 —
-- a mid-period reassignment or cost-code split), so a period genuinely can
-- have two rows for one mechanic. Faithfully preserved rather than merged.
-- ═══════════════════════════════════════════════════════════════════════
CREATE TABLE IF NOT EXISTS mechanic_kpi_snapshots (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  workshop_id       INT NOT NULL,
  mechanic_id       INT NOT NULL,
  period_start      DATE NOT NULL,
  period_end        DATE NOT NULL,
  employee_code     VARCHAR(20)  COMMENT 'Source TN-code, e.g. TN0269',
  designation       VARCHAR(50)  COMMENT 'Raw designation as reported (PAINTER, DENTER, ...)',
  days_present      INT,
  avail_hrs         DECIMAL(10,2),
  ot_hrs            DECIMAL(10,2),
  total_hrs         DECIMAL(10,2),
  worked_hrs        DECIMAL(10,2),
  prod_hrs_pct      DECIMAL(6,4)  COMMENT 'Stored as reported, e.g. 0.84 for 84%',
  idle_hrs_pct      DECIMAL(6,4),
  billed_value      DECIMAL(12,2),
  billed_hrs        DECIMAL(10,2),
  billed_hours      DECIMAL(10,2) COMMENT 'Distinct source column from billed_hrs, kept as reported',
  utilization_pct   DECIMAL(6,2)  COMMENT 'U% from the source report',
  productivity_pct  DECIMAL(6,2)  COMMENT 'P% from the source report',
  efficiency_pct    DECIMAL(6,2)  COMMENT 'E% from the source report',
  source            VARCHAR(30) DEFAULT 'manual_import',
  imported_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_workshop (workshop_id),
  INDEX idx_mechanic_period (mechanic_id, period_start, period_end),
  CONSTRAINT fk_mks_workshop FOREIGN KEY (workshop_id) REFERENCES workshops(id) ON DELETE CASCADE,
  CONSTRAINT fk_mks_mechanic FOREIGN KEY (mechanic_id) REFERENCES mechanics(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
